---
name: fabric-network-${ORG}
version: 1.0.0
client:
  organization: ${ORG}
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  ${ORG}:
    mspid: ${MSPID}
    peers:
    - peer0.${ORG}.aomd.com
    certificateAuthorities:
    - ca.${ORG}.aomd.com
peers:
  peer0.${ORG}.aomd.com:
    url: grpcs://localhost:${P0PORT}
    tlsCACerts:
      pem: |
          ${PEERPEM}
    grpcOptions:
      ssl-target-name-override: peer0.${ORG}.aomd.com
      hostnameOverride: peer0.${ORG}.aomd.com
certificateAuthorities:
  ca.${ORG}.aomd.com:
    url: https://localhost:${CAPORT}
    caName: ca-${ORG}
    tlsCACerts:
      pem: 
        - |
          ${CAPEM}
    httpOptions:
      verify: false
